RESEARCH_TOPIC = [
  {"topic": "Efficient training algorithms for large-scale transformer models", "subject": "CS-AI/ML"},
  {"topic": "Data-centric noise-robust learning pipelines", "subject": "CS-AI/ML"},
  {"topic": "Generalization theory for overparameterized networks", "subject": "CS-AI/ML"},
  {"topic": "Optimization landscapes for deep models", "subject": "CS-AI/ML"},
  {"topic": "Reinforcement learning with sparse rewards", "subject": "CS-AI/ML"},
  {"topic": "Multi-agent communication protocols", "subject": "CS-AI/ML"},
  {"topic": "Offline RL with safety constraints", "subject": "CS-AI/ML"},
  {"topic": "Hierarchical RL for long-horizon tasks", "subject": "CS-AI/ML"},
  {"topic": "Model compression for foundation models", "subject": "CS-AI/ML"},
  {"topic": "Multi-modal fusion architectures", "subject": "CS-AI/ML"},
  {"topic": "Continual learning benchmarks", "subject": "CS-AI/ML"},
  {"topic": "Adversarial robustness evaluation", "subject": "CS-AI/ML"},
  {"topic": "Privacy-preserving federated learning", "subject": "CS-AI/ML"},
  {"topic": "Explainable AI via concept-based methods", "subject": "CS-AI/ML"},
  {"topic": "Alignment methods for LLM agents", "subject": "CS-AI/ML"},
  {"topic": "RLHF optimization and stability analysis", "subject": "CS-AI/ML"},
  {"topic": "Generative models for structured data", "subject": "CS-AI/ML"},
  {"topic": "Diffusion model acceleration", "subject": "CS-AI/ML"},
  {"topic": "Active learning pipeline optimization", "subject": "CS-AI/ML"},
  {"topic": "Automated dataset cleaning", "subject": "CS-AI/ML"},
  {"topic": "Evaluation of large-scale generative text models", "subject": "CS-AI/ML"},
  {"topic": "Calibration of probabilistic predictions", "subject": "CS-AI/ML"},
  {"topic": "Human-AI collaboration modeling", "subject": "CS-AI/ML"},
  {"topic": "Uncertainty quantification in ML systems", "subject": "CS-AI/ML"},
  {"topic": "Synthetic data generation for ML training", "subject": "CS-AI/ML"},
  {"topic": "Causal representation learning", "subject": "CS-AI/ML"},
  {"topic": "In-context learning behavior analysis", "subject": "CS-AI/ML"},
  {"topic": "Prompt optimization algorithms", "subject": "CS-AI/ML"},
  {"topic": "Knowledge editing techniques for LLMs", "subject": "CS-AI/ML"},
  {"topic": "RAG pipeline robustness", "subject": "CS-AI/ML"},
  {"topic": "Benchmarks for long-context reasoning", "subject": "CS-AI/ML"},
  {"topic": "Memory-augmented agents", "subject": "CS-AI/ML"},
  {"topic": "Curriculum learning for foundation models", "subject": "CS-AI/ML"},
  {"topic": "Ethical risk assessment frameworks", "subject": "CS-AI/ML"},
  {"topic": "Bias mitigation in text generation", "subject": "CS-AI/ML"},
  {"topic": "Safety protocols for autonomous agents", "subject": "CS-AI/ML"},
  {"topic": "Self-supervised learning for structured signals", "subject": "CS-AI/ML"},
  {"topic": "Multi-task learning scheduling", "subject": "CS-AI/ML"},
  {"topic": "Distributed ML training reliability", "subject": "CS-AI/ML"},
  {"topic": "Large-scale hyperparameter optimization", "subject": "CS-AI/ML"},

  {"topic": "Multilingual machine translation error analysis", "subject": "CS-NLP"},
  {"topic": "Low-resource MT data augmentation", "subject": "CS-NLP"},
  {"topic": "Information extraction from noisy text", "subject": "CS-NLP"},
  {"topic": "Document summarization benchmarking", "subject": "CS-NLP"},
  {"topic": "Long-document QA systems", "subject": "CS-NLP"},
  {"topic": "Retrieval-augmented QA algorithms", "subject": "CS-NLP"},
  {"topic": "Dialogue safety evaluation", "subject": "CS-NLP"},
  {"topic": "Conversational personalization modeling", "subject": "CS-NLP"},
  {"topic": "Emotion-aware dialogue systems", "subject": "CS-NLP"},
  {"topic": "Multi-hop reasoning datasets", "subject": "CS-NLP"},
  {"topic": "Speech-to-text alignment methods", "subject": "CS-NLP"},
  {"topic": "Code generation model evaluation", "subject": "CS-NLP"},
  {"topic": "Biomedical text mining", "subject": "CS-NLP"},
  {"topic": "Political text classification", "subject": "CS-NLP"},
  {"topic": "Cross-domain sentiment adaptation", "subject": "CS-NLP"},
  {"topic": "Story generation evaluation metrics", "subject": "CS-NLP"},
  {"topic": "Controlled text generation", "subject": "CS-NLP"},
  {"topic": "Knowledge-grounded dialogue", "subject": "CS-NLP"},
  {"topic": "Entity-centric document understanding", "subject": "CS-NLP"},
  {"topic": "Fact-checking with LLM agents", "subject": "CS-NLP"},
  {"topic": "Multilingual lexicon induction", "subject": "CS-NLP"},
  {"topic": "Abstractive summarization quality modeling", "subject": "CS-NLP"},
  {"topic": "Narrative structure analysis", "subject": "CS-NLP"},
  {"topic": "Topic segmentation algorithms", "subject": "CS-NLP"},
  {"topic": "Legal document QA", "subject": "CS-NLP"},
  {"topic": "Scientific text simplification", "subject": "CS-NLP"},
  {"topic": "Cross-lingual alignment learning", "subject": "CS-NLP"},
  {"topic": "Prompted MT for low-resource languages", "subject": "CS-NLP"},
  {"topic": "Memory-sensitive dialogue modeling", "subject": "CS-NLP"},
  {"topic": "Toxicity detection and mitigation in text", "subject": "CS-NLP"},

  {"topic": "Object detection under domain shift", "subject": "CS-CV"},
  {"topic": "Weakly supervised segmentation", "subject": "CS-CV"},
  {"topic": "Video action recognition", "subject": "CS-CV"},
  {"topic": "3D scene reconstruction", "subject": "CS-CV"},
  {"topic": "Self-supervised visual pretraining", "subject": "CS-CV"},
  {"topic": "Vision-language model alignment", "subject": "CS-CV"},
  {"topic": "Diffusion-based image editing", "subject": "CS-CV"},
  {"topic": "Visually grounded reasoning", "subject": "CS-CV"},
  {"topic": "Few-shot visual classification", "subject": "CS-CV"},
  {"topic": "Robustness to adversarial images", "subject": "CS-CV"},
  {"topic": "Human pose estimation", "subject": "CS-CV"},
  {"topic": "Medical imaging segmentation", "subject": "CS-CV"},
  {"topic": "Satellite image analysis", "subject": "CS-CV"},
  {"topic": "Visual anomaly detection", "subject": "CS-CV"},
  {"topic": "Video summarization algorithms", "subject": "CS-CV"},
  {"topic": "Real-time detection on edge devices", "subject": "CS-CV"},
  {"topic": "Visual captioning evaluation", "subject": "CS-CV"},
  {"topic": "Robotics perception stack", "subject": "CS-CV"},
  {"topic": "Vision-based navigation", "subject": "CS-CV"},
  {"topic": "Image quality assessment", "subject": "CS-CV"},

  {"topic": "Human-AI interaction evaluation", "subject": "CS-HCI"},
  {"topic": "Intelligent assistant usability testing", "subject": "CS-HCI"},
  {"topic": "Adaptive UI design", "subject": "CS-HCI"},
  {"topic": "Accessibility technologies for low-vision users", "subject": "CS-HCI"},
  {"topic": "Interactive data visualization systems", "subject": "CS-HCI"},
  {"topic": "User trust calibration in AI systems", "subject": "CS-HCI"},
  {"topic": "Behavioral logging and analysis", "subject": "CS-HCI"},
  {"topic": "Voice-driven interfaces", "subject": "CS-HCI"},
  {"topic": "Human-in-the-loop annotation workflows", "subject": "CS-HCI"},
  {"topic": "Collaborative writing tools with AI support", "subject": "CS-HCI"},

  {"topic": "Distributed training system optimization", "subject": "CS-Systems"},
  {"topic": "Efficient data pipeline orchestration", "subject": "CS-Systems"},
  {"topic": "Cloud cost-aware scheduling", "subject": "CS-Systems"},
  {"topic": "Fault tolerance in distributed computation", "subject": "CS-Systems"},
  {"topic": "Database indexing for large ML workloads", "subject": "CS-Systems"},
  {"topic": "Low-latency serving of foundation models", "subject": "CS-Systems"},
  {"topic": "Resource-aware model deployment", "subject": "CS-Systems"},
  {"topic": "Stream processing performance analysis", "subject": "CS-Systems"},
  {"topic": "Large-scale logging infrastructure", "subject": "CS-Systems"},
  {"topic": "Edge-cloud collaborative computing", "subject": "CS-Systems"},

  {"topic": "Differential privacy for ML models", "subject": "CS-Security"},
  {"topic": "Secure multiparty computation protocols", "subject": "CS-Security"},
  {"topic": "Adversarial attack detection", "subject": "CS-Security"},
  {"topic": "Cryptographic acceleration", "subject": "CS-Security"},
  {"topic": "Federated learning threat modeling", "subject": "CS-Security"},
  {"topic": "Privacy audits for training data", "subject": "CS-Security"},
  {"topic": "Secure data exchange frameworks", "subject": "CS-Security"},
  {"topic": "LLM jailbreak prevention", "subject": "CS-Security"},
  {"topic": "Cyber-physical system security", "subject": "CS-Security"},
  {"topic": "Steganography detection models", "subject": "CS-Security"},

  {"topic": "Optimization algorithms for constrained systems", "subject": "Mathematics"},
  {"topic": "Numerical PDE simulation pipelines", "subject": "Mathematics"},
  {"topic": "Probabilistic modeling for stochastic systems", "subject": "Mathematics"},
  {"topic": "Graph-theoretic structure analysis", "subject": "Mathematics"},
  {"topic": "Symbolic reasoning automation", "subject": "Mathematics"},

  {"topic": "Simulation of quantum systems", "subject": "Physics"},
  {"topic": "Photonics experiment design", "subject": "Physics"},
  {"topic": "Turbulence modeling workflows", "subject": "Physics"},
  {"topic": "Material property prediction", "subject": "Physics"},
  {"topic": "Plasma physics simulation", "subject": "Physics"},
  {"topic": "Nuclear measurement analysis", "subject": "Physics"},
  {"topic": "Soft-matter modeling", "subject": "Physics"},
  {"topic": "Experimental instrumentation calibration", "subject": "Physics"},
  {"topic": "Condensed matter structure inference", "subject": "Physics"},
  {"topic": "Astrophysical signal extraction", "subject": "Physics"},

  {"topic": "Reaction pathway modeling", "subject": "Chemistry"},
  {"topic": "Computational chemistry property prediction", "subject": "Chemistry"},
  {"topic": "Materials screening via ML", "subject": "Chemistry"},
  {"topic": "Organic synthesis planning", "subject": "Chemistry"},
  {"topic": "Catalytic efficiency analysis", "subject": "Chemistry"},
  {"topic": "Polymer design workflows", "subject": "Chemistry"},
  {"topic": "Electrochemical system modeling", "subject": "Chemistry"},
  {"topic": "Battery material evaluation", "subject": "Chemistry"},
  {"topic": "Molecular docking pipeline", "subject": "Chemistry"},
  {"topic": "Spectroscopy data interpretation", "subject": "Chemistry"},

  {"topic": "Gene regulatory network inference", "subject": "Biology"},
  {"topic": "Single-cell data analysis", "subject": "Biology"},
  {"topic": "Protein structure prediction evaluation", "subject": "Biology"},
  {"topic": "Evolutionary modeling", "subject": "Biology"},
  {"topic": "Metabolomics workflow optimization", "subject": "Biology"},
  {"topic": "Microbiome data processing", "subject": "Biology"},
  {"topic": "Ecological simulation", "subject": "Biology"},
  {"topic": "Experimental protocol design for wet labs", "subject": "Biology"},
  {"topic": "Disease pathway modeling", "subject": "Biology"},
  {"topic": "Biological image analysis", "subject": "Biology"},

  {"topic": "Structural simulation for civil engineering", "subject": "Engineering"},
  {"topic": "Bridge safety assessment", "subject": "Engineering"},
  {"topic": "Environmental risk forecasting", "subject": "Engineering"},
  {"topic": "Wireless communication optimization", "subject": "Engineering"},
  {"topic": "Signal denoising algorithms", "subject": "Engineering"},
  {"topic": "Renewable energy system modeling", "subject": "Engineering"},
  {"topic": "Robotics motion planning", "subject": "Engineering"},
  {"topic": "Robot manipulation evaluation", "subject": "Engineering"},
  {"topic": "Autonomous vehicle perception stack", "subject": "Engineering"},
  {"topic": "HVAC system optimization", "subject": "Engineering"},
  {"topic": "Sensor fusion algorithms", "subject": "Engineering"},
  {"topic": "Vibration analysis in mechanical systems", "subject": "Engineering"},
  {"topic": "UAV flight control modeling", "subject": "Engineering"},
  {"topic": "Fault diagnosis for mechanical systems", "subject": "Engineering"},
  {"topic": "Materials fatigue prediction", "subject": "Engineering"},

  {"topic": "Clinical trial statistical modeling", "subject": "Medical"},
  {"topic": "Medical imaging segmentation", "subject": "Medical"},
  {"topic": "Disease outbreak forecasting", "subject": "Medical"},
  {"topic": "Electronic health record mining", "subject": "Medical"},
  {"topic": "Biomarker discovery pipelines", "subject": "Medical"},
  {"topic": "Genomic data interpretation", "subject": "Medical"},
  {"topic": "Epidemiological model validation", "subject": "Medical"},
  {"topic": "Diagnostic model evaluation", "subject": "Medical"},
  {"topic": "Radiology workflow optimization", "subject": "Medical"},
  {"topic": "Healthcare resource allocation modeling", "subject": "Medical"},

  {"topic": "Causal inference in economic policy", "subject": "Economics"},
  {"topic": "Market prediction modeling", "subject": "Economics"},
  {"topic": "Behavioral economics experiment design", "subject": "Economics"},
  {"topic": "Trade flow analysis", "subject": "Economics"},
  {"topic": "Productivity measurement pipelines", "subject": "Economics"},

  {"topic": "Political ideology classification from text", "subject": "PoliticalScience"},
  {"topic": "Survey design optimization", "subject": "PoliticalScience"},
  {"topic": "Electoral forecasting", "subject": "PoliticalScience"},
  {"topic": "Policy impact assessment", "subject": "PoliticalScience"},
  {"topic": "Social media political discourse analysis", "subject": "PoliticalScience"},

  {"topic": "Cognitive experiment workflow", "subject": "Psychology"},
  {"topic": "Behavioral modeling", "subject": "Psychology"},
  {"topic": "Psychometric scale construction", "subject": "Psychology"},
  {"topic": "Longitudinal study design", "subject": "Psychology"},
  {"topic": "Emotion recognition experiments", "subject": "Psychology"},

  {"topic": "Historical document analysis", "subject": "Humanities"},
  {"topic": "Corpus-based linguistic evolution", "subject": "Humanities"},
  {"topic": "Thematic annotation of literature", "subject": "Humanities"},
  {"topic": "Archival data digitization workflows", "subject": "Humanities"},
  {"topic": "Historical trend modeling", "subject": "Humanities"}
]



TUTORING_TOPIC = [
  # -------------------- MATH (30) --------------------
  {"topic": "Number sense and estimation strategies", "subject": "Math"},
  {"topic": "Fractions, decimals, and percent reasoning", "subject": "Math"},
  {"topic": "Ratios, rates, and proportional thinking", "subject": "Math"},
  {"topic": "Algebraic expressions and simplification patterns", "subject": "Math"},
  {"topic": "Linear equations, inequalities, and modeling", "subject": "Math"},
  {"topic": "Systems of equations and constraints reasoning", "subject": "Math"},
  {"topic": "Functions as relationships between variables", "subject": "Math"},
  {"topic": "Quadratic reasoning and common factorization strategies", "subject": "Math"},
  {"topic": "Exponents, roots, and growth patterns", "subject": "Math"},
  {"topic": "Sequences and recurrence thinking", "subject": "Math"},
  {"topic": "Counting methods and combinatorial reasoning", "subject": "Math"},
  {"topic": "Logic, statements, and proof-style explanations", "subject": "Math"},
  {"topic": "Geometry reasoning with angles, triangles, and circles", "subject": "Math"},
  {"topic": "Area, volume, and scaling arguments", "subject": "Math"},
  {"topic": "Similarity and invariants in geometry problems", "subject": "Math"},
  {"topic": "Coordinate geometry through equations and constraints", "subject": "Math"},
  {"topic": "Vectors and basic geometric transformations", "subject": "Math"},
  {"topic": "Trigonometric reasoning in word problems", "subject": "Math"},
  {"topic": "Limits and the idea of change", "subject": "Math"},
  {"topic": "Derivatives as rates and sensitivity", "subject": "Math"},
  {"topic": "Integrals as accumulation and total change", "subject": "Math"},
  {"topic": "Optimization and finding best solutions under constraints", "subject": "Math"},
  {"topic": "Error checking, approximation, and sanity checks", "subject": "Math"},
  {"topic": "Translating word problems into mathematical models", "subject": "Math"},
  {"topic": "Strategies for multi-step problem solving", "subject": "Math"},
  {"topic": "Common misconceptions and debugging math solutions", "subject": "Math"},
  {"topic": "Mathematical reasoning with units and dimensional analysis", "subject": "Math"},
  {"topic": "Inequality techniques and bounding arguments", "subject": "Math"},
  {"topic": "Discrete math patterns for everyday reasoning", "subject": "Math"},
  {"topic": "Building solution templates for recurring problem types", "subject": "Math"},

  # -------------------- PROGRAMMING (30) --------------------
  {"topic": "Computational thinking and problem decomposition", "subject": "Programming"},
  {"topic": "Control flow reasoning and state tracing", "subject": "Programming"},
  {"topic": "Functions, parameters, and reusable abstractions", "subject": "Programming"},
  {"topic": "Data structures and representation choices", "subject": "Programming"},
  {"topic": "Algorithmic patterns for searching and filtering", "subject": "Programming"},
  {"topic": "Algorithmic patterns for aggregation and counting", "subject": "Programming"},
  {"topic": "Python data structures and idioms", "subject": "Programming"},
  {"topic": "Python functions, scope, and common pitfalls", "subject": "Programming"},
  {"topic": "Python debugging workflows from tracebacks to fixes", "subject": "Programming"},
  {"topic": "Writing tests in Python and designing edge cases", "subject": "Programming"},
  {"topic": "Text processing pipelines in Python", "subject": "Programming"},
  {"topic": "File and directory automation in Python", "subject": "Programming"},
  {"topic": "Working with APIs in Python and parsing responses", "subject": "Programming"},
  {"topic": "Code quality in Python: typing, style, and refactoring", "subject": "Programming"},
  {"topic": "String processing and text transformation tasks", "subject": "Programming"},
  {"topic": "File handling and structured text formats", "subject": "Programming"},
  {"topic": "Debugging from error messages to root causes", "subject": "Programming"},
  {"topic": "Testing strategies and designing good test cases", "subject": "Programming"},
  {"topic": "Refactoring for readability and maintainability", "subject": "Programming"},
  {"topic": "Writing clean code: naming, structure, and conventions", "subject": "Programming"},
  {"topic": "Basic object-oriented design and trade-offs", "subject": "Programming"},
  {"topic": "Functional programming ideas and pure functions", "subject": "Programming"},
  {"topic": "Error handling and building robust programs", "subject": "Programming"},
  {"topic": "Working with APIs and parsing responses", "subject": "Programming"},
  {"topic": "Performance intuition and avoiding inefficient patterns", "subject": "Programming"},
  {"topic": "Database fundamentals and query reasoning", "subject": "Programming"},
  {"topic": "Designing small command-line tools", "subject": "Programming"},
  {"topic": "Code review skills and constructive critique", "subject": "Programming"},
  {"topic": "Software documentation that supports users", "subject": "Programming"},
  {"topic": "Design trade-offs and technical decision making", "subject": "Programming"},

  # -------------------- DATA SCIENCE (20) --------------------
  {"topic": "From questions to datasets and measurable outcomes", "subject": "DataScience"},
  {"topic": "Data cleaning rules and reproducible preprocessing", "subject": "DataScience"},
  {"topic": "Exploratory analysis using textual summaries", "subject": "DataScience"},
  {"topic": "Feature thinking and representing information", "subject": "DataScience"},
  {"topic": "Train-validation-test thinking and leakage avoidance", "subject": "DataScience"},
  {"topic": "Overfitting, generalization, and model selection", "subject": "DataScience"},
  {"topic": "Error analysis and iterative improvement loops", "subject": "DataScience"},
  {"topic": "Baseline design and fair method comparisons", "subject": "DataScience"},
  {"topic": "Evaluation metrics matched to real objectives", "subject": "DataScience"},
  {"topic": "Interpreting probabilistic outputs and uncertainty", "subject": "DataScience"},
  {"topic": "Sampling, bias, and representativeness in data", "subject": "DataScience"},
  {"topic": "A/B testing logic and practical pitfalls", "subject": "DataScience"},
  {"topic": "Causal language and limits of observational data", "subject": "DataScience"},
  {"topic": "Experiment tracking and reproducibility practices", "subject": "DataScience"},
  {"topic": "Data documentation and dataset statements", "subject": "DataScience"},
  {"topic": "Ethics, privacy, and responsible data use", "subject": "DataScience"},
  {"topic": "Writing clear analysis reports with assumptions", "subject": "DataScience"},
  {"topic": "Communicating limitations without undermining value", "subject": "DataScience"},
  {"topic": "Data analysis in pandas: joins, groupby, and sanity checks", "subject": "DataScience"},
  {"topic": "Data validation rules and simple quality checks", "subject": "DataScience"},

  # -------------------- LIFE SKILLS (20) --------------------
  {"topic": "Goal setting and milestone planning for long projects", "subject": "LifeSkills"},
  {"topic": "Time management and prioritization under constraints", "subject": "LifeSkills"},
  {"topic": "Building habits and staying consistent", "subject": "LifeSkills"},
  {"topic": "Decision making frameworks for everyday choices", "subject": "LifeSkills"},
  {"topic": "Managing procrastination and follow-through", "subject": "LifeSkills"},
  {"topic": "Communication for coordination and expectation setting", "subject": "LifeSkills"},
  {"topic": "Conflict resolution and difficult conversations", "subject": "LifeSkills"},
  {"topic": "Personal budgeting and spending awareness", "subject": "LifeSkills"},
  {"topic": "Saving strategies and financial goal planning", "subject": "LifeSkills"},
  {"topic": "Understanding loans, interest, and debt decisions", "subject": "LifeSkills"},
  {"topic": "Evaluating online information and misinformation", "subject": "LifeSkills"},
  {"topic": "Digital safety habits and account protection", "subject": "LifeSkills"},
  {"topic": "Writing professional emails and short reports", "subject": "LifeSkills"},
  {"topic": "Interview preparation and structured self-presentation", "subject": "LifeSkills"},
  {"topic": "Career planning and skill development strategies", "subject": "LifeSkills"},
  {"topic": "Negotiating deadlines and scope changes", "subject": "LifeSkills"},
  {"topic": "Managing stress in demanding schedules", "subject": "LifeSkills"},
  {"topic": "Reflective practice and learning from mistakes", "subject": "LifeSkills"},
  {"topic": "Organizing personal workflows and task systems", "subject": "LifeSkills"},
  {"topic": "Building resilience and recovering from setbacks", "subject": "LifeSkills"},

  # -------------------- HEALTH (20) --------------------
  {"topic": "Building sustainable sleep routines", "subject": "Health"},
  {"topic": "Stress management habits and coping strategies", "subject": "Health"},
  {"topic": "Nutrition planning with realistic constraints", "subject": "Health"},
  {"topic": "Exercise planning for consistency and safety", "subject": "Health"},
  {"topic": "Understanding common health information and claims", "subject": "Health"},
  {"topic": "Evaluating health advice sources and credibility", "subject": "Health"},
  {"topic": "Health behavior change and habit formation", "subject": "Health"},
  {"topic": "Managing burnout and maintaining wellbeing in study and work", "subject": "Health"},
  {"topic": "Basic mental health literacy and self-care planning", "subject": "Health"},
  {"topic": "Communicating symptoms and concerns to professionals", "subject": "Health"},
  {"topic": "Preparing for a medical appointment and asking questions", "subject": "Health"},
  {"topic": "Understanding preventive care and routine checkups", "subject": "Health"},
  {"topic": "Managing screen time and digital wellbeing", "subject": "Health"},
  {"topic": "Building a personal wellness plan and tracking progress", "subject": "Health"},
  {"topic": "Work-life boundaries and recovery routines", "subject": "Health"},
  {"topic": "Understanding medication labels and general safety rules", "subject": "Health"},
  {"topic": "First aid principles and emergency decision logic", "subject": "Health"},
  {"topic": "Healthy eating in shared or limited environments", "subject": "Health"},
  {"topic": "Reducing sedentary time and improving daily movement", "subject": "Health"},
  {"topic": "Recognizing when to seek help and escalation pathways", "subject": "Health"},

  # -------------------- WRITING (20) --------------------
  {"topic": "Writing with clarity and avoiding ambiguity", "subject": "Writing"},
  {"topic": "Paragraph logic and coherent flow across sections", "subject": "Writing"},
  {"topic": "Building strong arguments with appropriate evidence", "subject": "Writing"},
  {"topic": "Outlining long documents for structure and consistency", "subject": "Writing"},
  {"topic": "Revision strategies for improving drafts efficiently", "subject": "Writing"},
  {"topic": "Editing for concision and removing redundancy", "subject": "Writing"},
  {"topic": "Tone control for professional and academic contexts", "subject": "Writing"},
  {"topic": "Writing summaries and paraphrases that preserve meaning", "subject": "Writing"},
  {"topic": "Writing explanations of technical ideas for mixed audiences", "subject": "Writing"},
  {"topic": "Academic writing conventions across disciplines", "subject": "Writing"},
  {"topic": "Writing introductions that motivate and scope a piece", "subject": "Writing"},
  {"topic": "Writing methods and procedures readers can follow", "subject": "Writing"},
  {"topic": "Writing results and discussing limitations responsibly", "subject": "Writing"},
  {"topic": "Responding to feedback and planning revisions", "subject": "Writing"},
  {"topic": "Writing short reports and progress updates", "subject": "Writing"},
  {"topic": "Writing technical documentation for users", "subject": "Writing"},
  {"topic": "Avoiding overclaiming and qualifying statements properly", "subject": "Writing"},
  {"topic": "Citations, attribution, and avoiding plagiarism", "subject": "Writing"},
  {"topic": "Consistency in terminology and definitions", "subject": "Writing"},
  {"topic": "Common writing errors and self-editing checklists", "subject": "Writing"},

  # -------------------- PHYSICS (10) --------------------
  {"topic": "Forces, motion, and building physical explanations", "subject": "Physics"},
  {"topic": "Energy and conservation principles in reasoning problems", "subject": "Physics"},
  {"topic": "Momentum and collision reasoning in text problems", "subject": "Physics"},
  {"topic": "Electric circuits described verbally and qualitatively", "subject": "Physics"},
  {"topic": "Waves and oscillations as patterns and models", "subject": "Physics"},
  {"topic": "Optics reasoning without diagrams using careful descriptions", "subject": "Physics"},
  {"topic": "Fluids, pressure, and buoyancy in everyday scenarios", "subject": "Physics"},
  {"topic": "Thermal processes and heat transfer explanations", "subject": "Physics"},
  {"topic": "Units, dimensions, and sanity checks in physics", "subject": "Physics"},
  {"topic": "Multi-step physics word problems and solution habits", "subject": "Physics"},

  # -------------------- CHEMISTRY (10) --------------------
  {"topic": "Atomic structure and bonding explanations", "subject": "Chemistry"},
  {"topic": "Stoichiometry as conservation and bookkeeping", "subject": "Chemistry"},
  {"topic": "Acids, bases, and pH reasoning in scenarios", "subject": "Chemistry"},
  {"topic": "Reaction rates and factors influencing change", "subject": "Chemistry"},
  {"topic": "Chemical equilibrium and system responses", "subject": "Chemistry"},
  {"topic": "Solutions and concentration reasoning in text problems", "subject": "Chemistry"},
  {"topic": "Redox reasoning and electron transfer narratives", "subject": "Chemistry"},
  {"topic": "Energy changes in reactions and interpretation", "subject": "Chemistry"},
  {"topic": "Organic chemistry patterns and reaction logic in words", "subject": "Chemistry"},
  {"topic": "Explaining chemistry mechanisms clearly and precisely", "subject": "Chemistry"},

  # -------------------- HISTORY (10) --------------------
  {"topic": "Building historical explanations using cause and effect", "subject": "History"},
  {"topic": "Comparing historical periods through themes", "subject": "History"},
  {"topic": "Institutional change and political development over time", "subject": "History"},
  {"topic": "Economic and technological change in societies", "subject": "History"},
  {"topic": "Revolutions and social transformation", "subject": "History"},
  {"topic": "War, diplomacy, and shifting alliances in narratives", "subject": "History"},
  {"topic": "Colonialism and long-term consequences", "subject": "History"},
  {"topic": "Industrialization and the modern world", "subject": "History"},
  {"topic": "Evaluating historical sources and perspectives in text", "subject": "History"},
  {"topic": "Writing structured historical arguments and essays", "subject": "History"},

  # -------------------- POLITICAL SCIENCE (10) --------------------
  {"topic": "How governments function and make policy decisions", "subject": "PoliticalScience"},
  {"topic": "Elections, representation, and political incentives", "subject": "PoliticalScience"},
  {"topic": "Public policy trade-offs and unintended consequences", "subject": "PoliticalScience"},
  {"topic": "Political ideologies and how arguments are framed", "subject": "PoliticalScience"},
  {"topic": "Institutions, checks and balances, and accountability", "subject": "PoliticalScience"},
  {"topic": "Media literacy for political information", "subject": "PoliticalScience"},
  {"topic": "Persuasion, rhetoric, and political communication", "subject": "PoliticalScience"},
  {"topic": "Civic participation and collective action reasoning", "subject": "PoliticalScience"},
  {"topic": "Comparing political systems using clear criteria", "subject": "PoliticalScience"},
  {"topic": "Writing balanced policy arguments with evidence", "subject": "PoliticalScience"},

  # -------------------- ECONOMICS (10) --------------------
  {"topic": "Incentives, trade-offs, and decision making", "subject": "Economics"},
  {"topic": "Supply, demand, and how markets coordinate behavior", "subject": "Economics"},
  {"topic": "Inflation, interest rates, and household impacts", "subject": "Economics"},
  {"topic": "Economic growth, productivity, and living standards", "subject": "Economics"},
  {"topic": "Market failures and the role of regulation", "subject": "Economics"},
  {"topic": "Trade and globalization as resource allocation", "subject": "Economics"},
  {"topic": "Inequality, mobility, and distributional effects", "subject": "Economics"},
  {"topic": "Cost-benefit thinking for policy and personal choices", "subject": "Economics"},
  {"topic": "Interpreting economic claims and evidence carefully", "subject": "Economics"},
  {"topic": "Writing short economics answers with explicit assumptions", "subject": "Economics"},

  # -------------------- BIOLOGY (10) --------------------
  {"topic": "Cell function and how living systems maintain stability", "subject": "Biology"},
  {"topic": "Genetics as information flow across generations", "subject": "Biology"},
  {"topic": "Evolution and adaptation as explanatory frameworks", "subject": "Biology"},
  {"topic": "Human physiology as interacting systems", "subject": "Biology"},
  {"topic": "Immunity, infection, and host-pathogen reasoning", "subject": "Biology"},
  {"topic": "Metabolism and energy use in organisms", "subject": "Biology"},
  {"topic": "Ecology and stability in ecosystems", "subject": "Biology"},
  {"topic": "Experimental thinking and evidence in biology", "subject": "Biology"},
  {"topic": "Reading biology questions and answering with justification", "subject": "Biology"},
  {"topic": "Writing clear biological explanations in paragraph form", "subject": "Biology"},
]